modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="titanium"
version="1.0.0"
displayName="Titanium"
# logoFile="titanium.png" #optional
description='''
Adds titanium as a new ore to the game.
'''
[[dependencies.titanium]] #optional
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.titanium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
